language:
  - go
  - c
sudo: true
go:
  - 1.13
compiler:
  - gcc-7

os:
  - linux
  - osx
  - windows

install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install visualstudio2017-workload-vctools -y; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh travis-clang.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then sh travis-cl.sh; fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh travis-clang.sh; fi
