name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./lib
        ./test.sh
        popd
    - name: build cmd
      run: |
        pushd ./cmd
        ./build.sh
        popd
