name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        go test .
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        go build .
        popd

  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        go test .
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        go build .
        popd

  win32:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        go test .
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        go build .
        popd
