name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        ./test.sh
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        ./build.sh
        popd

  linux:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        ./test.sh
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        ./build.sh
        popd

  win32:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        pushd ./longtaillib
        ./test.bat
        popd
    - name: build cmd
      run: |
        pushd ./cmd/longtail
        ./build.bat
        popd
